Improve SoundDidFinishPlayingNotification by including completion success in notification
recisio/AudioPlayerSwift pull request #29
Opened 2018-10-08 19:05 UTC by jashenson

Modules wanting to be notified about the completion of an AudioPlayer playing a sound have two options:
1. Provide completion handler, but only be notified about whether play completed successfully
2. Register for NotificationCenter, but only be notified about the player that completed

This creates an issue when the module wants to do something specifically based on the completion success while not knowing which of potentially multiple AudioPlayers is sending the message.

Fixing #1 requires changing the method signature. While I would encourage this to be implemented as it makes the completion handler more powerful, it will break the current API. 

Fixing #2 is easy and non-breaking. I have implemented this here by adding a userInfo dictionary to the Notification including the boolean completion success.

---

I have also made a few small code changes to the init methods to use best Swift practices.

2018-10-09 06:33 UTC, tbaranes requested changes
All good! Could you just add an entry to the CHANGELOG?
Travis seems to be failing, I'm restarting the failing jobs, doesn't seem to be related to this PR.

2018-10-09 16:02 UTC, jashenson commented
Updated CHANGELOG as requested.

2018-10-10 06:45 UTC, tbaranes approved these changes

2018-10-10 06:48 UTC, tbaranes commented
Travis is failing due to Swiftlint, which doesn't make sense (I checked it locally), will merge anyway. Thanks for your PR!

2018-10-10 06:48 UTC, merged